name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O el nom de la teva branca principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar el repositori
        uses: actions/checkout@v3

      - name: âš™ï¸ InstalÂ·lar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ”„ Generar stickers.json
        run: node generate_stickers.js

      - name: ğŸš€ Deploy a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Branca on GitHub Pages estÃ  activat
          folder: . # Desplegar tota la web
