name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Canvia-ho si tens una altra branca principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar el repositori
        uses: actions/checkout@v3

      - name: âš™ï¸ InstalÂ·lar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ğŸ”„ Generar stickers.json
        run: node generate_stickers.js

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: ğŸš€ Deploy a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: . # Carpeta amb el contingut a desplegar
          clean: true
